web:
  image: resultadosdigitais/API_NAME_HERE-dev:alpha
  command: bash -c "/var/app/script/server"
  volumes:
    - .:/var/app
  ports:
   - "80:9393"
  environment:
    DATABASE_URL: 'postgres://vikings:8ATey2YhBHuLTjuu@segmentation-ops.cmd5nferbuoj.us-east-1.rds.amazonaws.com:5432/segmentation'
    LOGGER_FILE: 'log/API_NAME_HERE.log'
    WEB_SERVER_PORT: '9393'
    RACK_ENV: development
    HTTP_CACHE_EXPIRATION: 10
