api:
  image: resultadosdigitais/{{API_NAME_HERE}}:latest
  command: "./entrypoint.sh"
  restart: always
  volumes:
    - .:/var/app
  links:
    - db
  ports:
   - "80:9393"
  environment:
    DATABASE_URL: 'postgres://postgres@db:5432/api_db'
    LOGGER_FILE: 'log/{{API_NAME_HERE}}.log'
    WEB_SERVER_PORT: '9393'
    RACK_ENV: development
    HTTP_CACHE_EXPIRATION: 120
db:
  image: postgres:9.4.4
  volumes:
    - {{API_NAME_HERE}}-postgres:/var/lib/postgresql/data
