api:
  image: resultadosdigitais/{{API_NAME_HERE}}:latest-dev
  command: "./entrypoint.sh"
  restart: always
  volumes:
    - ~:/root
    - .:/var/app
  links:
    - db
  ports:
   - "80:9393"
  environment:
    DATABASE_URL: 'postgres://postgres@db/{{API_NAME_HERE}}_db'
    LOGGER_FILE: 'log/{{API_NAME_HERE}}.log'
    WEB_SERVER_PORT: '9393'
    RACK_ENV: development
db:
  image: postgres:9.4.4
  volumes:
    - ~:/root
    - {{API_NAME_HERE}}_postgres:/var/lib/postgresql/data
