api:
  image: resultadosdigitais/{{API_NAME_HERE}}:{{IMAGE_TAG}}
  command: "./entrypoint.sh"
  restart: always
  volumes:
    - .:/var/app
  links:
    - db
  ports:
   - "{{API_SERVER_PORT_EXPOSED}}:{{API_SERVER_PORT}}"
  environment:
    DATABASE_URL: 'postgres://postgres@db:5432/api_db'
    LOGGER_FILE: 'log/{{API_NAME_HERE}}.log'
    WEB_SERVER_PORT: '{{API_SERVER_PORT}}'
    RACK_ENV: {{APP_ENVIRONMENT}}
    HTTP_CACHE_EXPIRATION: {{HTTP_CACHE_EXPIRATION}}

db:
  image: postgres:9.4.4
  volumes:
    - {{API_NAME_HERE}}-postgres:/var/lib/postgresql/data
