api:
  image: hugoluchessi/rest_api_template:latest-dev
  command: "./entrypoint.sh"
  restart: always
  volumes:
    - ~:/root
    - .:/var/app
  links:
    - db
  ports:
   - "80:9393"
  environment:
    DATABASE_URL: 'postgres://postgres@db/rest_api_template_db'
    LOGGER_FILE: 'log/rest_api_template.log'
    WEB_SERVER_PORT: '9393'
    RACK_ENV: development
db:
  image: postgres:9.4.4
  volumes:
    - ~:/root
    - rest_api_template_postgres:/var/lib/postgresql/data
