api:
  image: hugo1987br/rest_api_template:latest-dev
  command: "sh ./script/entrypoint.sh"
  restart: always
  volumes:
    - ~:/root
    - .:/var/app
  links:
    - db
  ports:
   - "8080:9393"
  environment:
    DATABASE_URL: 'postgres://postgres@db/rest_api_template_db'
    LOGGER_FILE: 'log/rest_api_template.log'
    UNICORN_WEB_TIMEOUT: 6000
    UNICORN_WORKER_PROCESSES: 3
    UNICORN_WEB_SERVER_PORT: '9393'
    RACK_ENV: development
db:
  image: postgres:9.4.4
  volumes:
    - ~:/root
    - rest_api_template_postgres:/var/lib/postgresql/data
